/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tmcs_msg.RPC', null, global);
goog.exportSymbol('proto.tmcs_msg.RPCCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tmcs_msg.RPC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tmcs_msg.RPC.oneofGroups_);
};
goog.inherits(proto.tmcs_msg.RPC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tmcs_msg.RPC.displayName = 'proto.tmcs_msg.RPC';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tmcs_msg.RPC.oneofGroups_ = [[4,5]];

/**
 * @enum {number}
 */
proto.tmcs_msg.RPC.DataCase = {
  DATA_NOT_SET: 0,
  TEXTDATA: 4,
  BINDATA: 5
};

/**
 * @return {proto.tmcs_msg.RPC.DataCase}
 */
proto.tmcs_msg.RPC.prototype.getDataCase = function() {
  return /** @type {proto.tmcs_msg.RPC.DataCase} */(jspb.Message.computeOneofCase(this, proto.tmcs_msg.RPC.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tmcs_msg.RPC.prototype.toObject = function(opt_includeInstance) {
  return proto.tmcs_msg.RPC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tmcs_msg.RPC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tmcs_msg.RPC.toObject = function(includeInstance, msg) {
  var obj = {
    rpcid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    code: jspb.Message.getFieldWithDefault(msg, 2, 0),
    message: jspb.Message.getFieldWithDefault(msg, 3, ""),
    textdata: jspb.Message.getFieldWithDefault(msg, 4, ""),
    bindata: msg.getBindata_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tmcs_msg.RPC}
 */
proto.tmcs_msg.RPC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tmcs_msg.RPC;
  return proto.tmcs_msg.RPC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tmcs_msg.RPC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tmcs_msg.RPC}
 */
proto.tmcs_msg.RPC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRpcid(value);
      break;
    case 2:
      var value = /** @type {!proto.tmcs_msg.RPCCode} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextdata(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBindata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tmcs_msg.RPC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tmcs_msg.RPC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tmcs_msg.RPC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tmcs_msg.RPC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRpcid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional int32 rpcId = 1;
 * @return {number}
 */
proto.tmcs_msg.RPC.prototype.getRpcid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tmcs_msg.RPC.prototype.setRpcid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional RPCCode code = 2;
 * @return {!proto.tmcs_msg.RPCCode}
 */
proto.tmcs_msg.RPC.prototype.getCode = function() {
  return /** @type {!proto.tmcs_msg.RPCCode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.tmcs_msg.RPCCode} value */
proto.tmcs_msg.RPC.prototype.setCode = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.tmcs_msg.RPC.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.tmcs_msg.RPC.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string textData = 4;
 * @return {string}
 */
proto.tmcs_msg.RPC.prototype.getTextdata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.tmcs_msg.RPC.prototype.setTextdata = function(value) {
  jspb.Message.setOneofField(this, 4, proto.tmcs_msg.RPC.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.tmcs_msg.RPC.prototype.clearTextdata = function() {
  jspb.Message.setOneofField(this, 4, proto.tmcs_msg.RPC.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tmcs_msg.RPC.prototype.hasTextdata = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bytes binData = 5;
 * @return {!(string|Uint8Array)}
 */
proto.tmcs_msg.RPC.prototype.getBindata = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes binData = 5;
 * This is a type-conversion wrapper around `getBindata()`
 * @return {string}
 */
proto.tmcs_msg.RPC.prototype.getBindata_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBindata()));
};


/**
 * optional bytes binData = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBindata()`
 * @return {!Uint8Array}
 */
proto.tmcs_msg.RPC.prototype.getBindata_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBindata()));
};


/** @param {!(string|Uint8Array)} value */
proto.tmcs_msg.RPC.prototype.setBindata = function(value) {
  jspb.Message.setOneofField(this, 5, proto.tmcs_msg.RPC.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.tmcs_msg.RPC.prototype.clearBindata = function() {
  jspb.Message.setOneofField(this, 5, proto.tmcs_msg.RPC.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tmcs_msg.RPC.prototype.hasBindata = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.tmcs_msg.RPCCode = {
  PING: 0,
  PONG: 1,
  LINKCLICKED: 2000,
  CONTACTREQUEST: 2001,
  CONTACTONLINE: 2002,
  CONTACTOFFLINE: 2003
};

goog.object.extend(exports, proto.tmcs_msg);
