// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmcs_error.proto

package tmcs_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_None                ErrorCode = 0
	ErrorCode_InvalidMessage      ErrorCode = 1000
	ErrorCode_MessageNotDelivered ErrorCode = 1001
	ErrorCode_ReceiverUnknown     ErrorCode = 1002
	ErrorCode_VerifyError         ErrorCode = 1003
	ErrorCode_InvalidKey          ErrorCode = 1004
	ErrorCode_InternalError       ErrorCode = 5000
)

var ErrorCode_name = map[int32]string{
	0:    "None",
	1000: "InvalidMessage",
	1001: "MessageNotDelivered",
	1002: "ReceiverUnknown",
	1003: "VerifyError",
	1004: "InvalidKey",
	5000: "InternalError",
}

var ErrorCode_value = map[string]int32{
	"None":                0,
	"InvalidMessage":      1000,
	"MessageNotDelivered": 1001,
	"ReceiverUnknown":     1002,
	"VerifyError":         1003,
	"InvalidKey":          1004,
	"InternalError":       5000,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_52b988334f8aa295, []int{0}
}

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=tmcs_msg.ErrorCode" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_52b988334f8aa295, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_None
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("tmcs_msg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Error)(nil), "tmcs_msg.Error")
}

func init() { proto.RegisterFile("tmcs_error.proto", fileDescriptor_52b988334f8aa295) }

var fileDescriptor_52b988334f8aa295 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x09, 0x04, 0xdc, 0x1e, 0xa2, 0x3d, 0x5d, 0x18, 0x3c, 0x22, 0x96, 0x22, 0x86, 0x0c,
	0xf0, 0x08, 0xc0, 0x50, 0x21, 0x3a, 0x44, 0x82, 0x11, 0x64, 0xe2, 0xa3, 0x8a, 0x48, 0x6c, 0x64,
	0x5b, 0x45, 0x7d, 0x03, 0x56, 0xde, 0x92, 0x7f, 0x0f, 0x81, 0xeb, 0x36, 0xdd, 0xfc, 0x7d, 0xdf,
	0xcf, 0xdf, 0x9d, 0x0e, 0x30, 0x74, 0xb5, 0x7f, 0x62, 0xe7, 0xac, 0x2b, 0xdf, 0x9c, 0x0d, 0x96,
	0x06, 0xc9, 0xe9, 0xfc, 0xfc, 0xf4, 0x11, 0xf6, 0x6f, 0x56, 0x01, 0x4d, 0x20, 0xaf, 0xad, 0x66,
	0x99, 0x9d, 0x64, 0x67, 0xa3, 0x8b, 0xa2, 0xec, 0x89, 0x32, 0xc5, 0x57, 0x31, 0xaa, 0x12, 0x40,
	0x12, 0x44, 0xc7, 0xde, 0xab, 0x39, 0xcb, 0xdd, 0xc8, 0x0e, 0xab, 0x5e, 0x12, 0x41, 0xae, 0x55,
	0x50, 0x72, 0x2f, 0xd9, 0xe9, 0x7d, 0xfe, 0x99, 0xc1, 0x70, 0xdb, 0x40, 0x03, 0xc8, 0x67, 0xd6,
	0x30, 0xee, 0x50, 0x01, 0xa3, 0xa9, 0x59, 0xa8, 0xb6, 0xd1, 0x77, 0xeb, 0xdf, 0xf8, 0x25, 0x62,
	0x75, 0xb1, 0x51, 0x33, 0x1b, 0xae, 0xb9, 0x6d, 0x16, 0xec, 0x58, 0xe3, 0xb7, 0xa0, 0x63, 0x18,
	0x57, 0x5c, 0xf3, 0xca, 0xb8, 0x37, 0xaf, 0xc6, 0xbe, 0x1b, 0xfc, 0x11, 0x84, 0x70, 0xf8, 0xc0,
	0xae, 0x79, 0x59, 0xa6, 0x09, 0xf8, 0x2b, 0x68, 0x0c, 0xb0, 0xa9, 0xbd, 0xe5, 0x25, 0xfe, 0x89,
	0xb8, 0xd3, 0xd1, 0xd4, 0x04, 0x76, 0x46, 0xb5, 0x6b, 0xe8, 0x63, 0xf2, 0x7c, 0x90, 0x8e, 0x70,
	0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xee, 0x8a, 0x6a, 0xed, 0x18, 0x01, 0x00, 0x00,
}
