// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmcs_rpc.proto

package tmcs_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCCode int32

const (
	RPCCode_Ping           RPCCode = 0
	RPCCode_Pong           RPCCode = 1
	RPCCode_LinkClicked    RPCCode = 2000
	RPCCode_ContactRequest RPCCode = 2001
	RPCCode_ContactOnline  RPCCode = 2002
	RPCCode_ContactOffline RPCCode = 2003
)

var RPCCode_name = map[int32]string{
	0:    "Ping",
	1:    "Pong",
	2000: "LinkClicked",
	2001: "ContactRequest",
	2002: "ContactOnline",
	2003: "ContactOffline",
}

var RPCCode_value = map[string]int32{
	"Ping":           0,
	"Pong":           1,
	"LinkClicked":    2000,
	"ContactRequest": 2001,
	"ContactOnline":  2002,
	"ContactOffline": 2003,
}

func (x RPCCode) String() string {
	return proto.EnumName(RPCCode_name, int32(x))
}

func (RPCCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89cbeccdfc94c509, []int{0}
}

type RPC struct {
	RpcId   int32   `protobuf:"varint,1,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
	Code    RPCCode `protobuf:"varint,2,opt,name=code,proto3,enum=tmcs_msg.RPCCode" json:"code,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*RPC_TextData
	//	*RPC_BinData
	Data                 isRPC_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_89cbeccdfc94c509, []int{0}
}

func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (m *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(m, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *RPC) GetCode() RPCCode {
	if m != nil {
		return m.Code
	}
	return RPCCode_Ping
}

func (m *RPC) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isRPC_Data interface {
	isRPC_Data()
}

type RPC_TextData struct {
	TextData string `protobuf:"bytes,4,opt,name=textData,proto3,oneof"`
}

type RPC_BinData struct {
	BinData []byte `protobuf:"bytes,5,opt,name=binData,proto3,oneof"`
}

func (*RPC_TextData) isRPC_Data() {}

func (*RPC_BinData) isRPC_Data() {}

func (m *RPC) GetData() isRPC_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RPC) GetTextData() string {
	if x, ok := m.GetData().(*RPC_TextData); ok {
		return x.TextData
	}
	return ""
}

func (m *RPC) GetBinData() []byte {
	if x, ok := m.GetData().(*RPC_BinData); ok {
		return x.BinData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RPC) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RPC_TextData)(nil),
		(*RPC_BinData)(nil),
	}
}

func init() {
	proto.RegisterEnum("tmcs_msg.RPCCode", RPCCode_name, RPCCode_value)
	proto.RegisterType((*RPC)(nil), "tmcs_msg.RPC")
}

func init() { proto.RegisterFile("tmcs_rpc.proto", fileDescriptor_89cbeccdfc94c509) }

var fileDescriptor_89cbeccdfc94c509 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x57, 0xd7, 0xae, 0xf5, 0xa8, 0x6d, 0x3c, 0x7a, 0x11, 0xc4, 0x0b, 0x11, 0x04, 0xf1,
	0xa2, 0x17, 0xfa, 0x06, 0xd6, 0x0b, 0x05, 0x61, 0x23, 0x2f, 0x20, 0x5d, 0x9a, 0x95, 0xb0, 0x25,
	0x99, 0x4b, 0x04, 0x9f, 0xc6, 0x67, 0xf2, 0xcf, 0x0b, 0x79, 0x8c, 0xab, 0x78, 0x95, 0xf3, 0xfd,
	0x7e, 0xe7, 0x23, 0x70, 0xa0, 0x0c, 0x46, 0xfa, 0xa7, 0xcd, 0x5a, 0xd6, 0xeb, 0x8d, 0x0b, 0x0e,
	0x8b, 0x98, 0x8d, 0xef, 0xcf, 0xdf, 0x12, 0x18, 0x8b, 0x59, 0x83, 0xc7, 0x90, 0x91, 0x7e, 0xe8,
	0x78, 0x72, 0x96, 0x5c, 0x66, 0xe2, 0x37, 0xe0, 0x05, 0xa4, 0xd2, 0x75, 0x8a, 0xef, 0x10, 0x2c,
	0xaf, 0x0f, 0xeb, 0xa1, 0x56, 0x53, 0xa5, 0x21, 0x21, 0xa2, 0x46, 0x0e, 0xb9, 0x51, 0xde, 0xb7,
	0xbd, 0xe2, 0x63, 0xda, 0xdc, 0x15, 0x43, 0xc4, 0x53, 0x28, 0x82, 0x7a, 0x0d, 0x77, 0x6d, 0x68,
	0x79, 0xfa, 0xa3, 0xee, 0x47, 0xe2, 0x8f, 0xe0, 0x09, 0xe4, 0x73, 0x6d, 0xa3, 0xcc, 0x48, 0xee,
	0x93, 0x1c, 0xc0, 0xed, 0x04, 0xd2, 0x8e, 0xde, 0x2b, 0x03, 0xf9, 0xf6, 0x33, 0x2c, 0x20, 0x9d,
	0x69, 0xdb, 0xb3, 0x51, 0x9c, 0x1c, 0x4d, 0x09, 0x32, 0xd8, 0x7b, 0xd4, 0x76, 0xd9, 0xac, 0xb4,
	0x5c, 0xaa, 0x8e, 0xbd, 0x57, 0x78, 0x04, 0x65, 0xe3, 0x6c, 0x68, 0x65, 0x10, 0xea, 0xf9, 0x45,
	0xf9, 0xc0, 0x3e, 0x2a, 0x44, 0x38, 0xd8, 0xc2, 0xa9, 0x5d, 0x69, 0xab, 0xd8, 0xe7, 0xff, 0xc5,
	0xe9, 0x62, 0x11, 0xe1, 0x57, 0x35, 0x9f, 0xc4, 0x03, 0xdd, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x20, 0xd5, 0xd7, 0x32, 0x01, 0x00, 0x00,
}
